name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  deploy-project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Clean install dependencies
        run: npm ci

      - name: build project
        run: npm run build

     # Deploys the built project to the gh\-pages branch
      - name: Deploy to GitHub Pages
        run: |
          cd dist
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ github.actor }}"
          git init
          git add -A
          git commit -m 'Automated deployment'
          git push -f https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git master:gh-pages
        shell: bash